# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}

  service:
    build:
      context: ..
      dockerfile: notification-server/scripts/Dockerfile
    restart: always
    entrypoint: ["./notification-service"]
    environment:
      NOTIFICATION_SERVER_DB_CONNECTION: postgres://postgres:${PGPASSWORD}@db:5432/postgres

  api:
    build:
      context: ..
      dockerfile: notification-server/scripts/Dockerfile
    restart: always
    ports:
      - "13030:3030"
    entrypoint: ["./notification-api"]
    environment:
      NOTIFICATION_SERVER_DB_CONNECTION: postgres://postgres:${PGPASSWORD}@db:5432/postgres
