CREATE TABLE IF NOT EXISTS blocks (
  id SERIAL8 PRIMARY KEY,
  hash BYTEA NOT NULL UNIQUE,
  timestamp INT8 NOT NULL,
  height INT8 NOT NULL,
  total_stake INT8 -- NULL means the block is NOT a payday block.
);

CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL8 PRIMARY KEY,
  address BYTEA NOT NULL UNIQUE,
  block INT8 NOT NULL REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  is_initial BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS modules (
  id SERIAL8 PRIMARY KEY,
  ref BYTEA NOT NULL UNIQUE,
  block INT8 NOT NULL REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS contracts (
  id SERIAL8 PRIMARY KEY,
  index INT8 NOT NULL,
  subindex INT8 NOT NULL,
  module BYTEA NOT NULL,
  block INT8 NOT NULL REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE (index, subindex)
);

CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL8 PRIMARY KEY,
  hash BYTEA NOT NULL UNIQUE,
  block INT8 NOT NULL REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  type INT2 -- NULL means the transaction was rejected
);

CREATE TABLE IF NOT EXISTS accounts_blocks (
  account INT8 REFERENCES accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  block INT8 REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  PRIMARY KEY (account, block)
);

CREATE TABLE IF NOT EXISTS contracts_blocks (
  contract INT8 REFERENCES contracts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  block INT8 REFERENCES blocks(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  PRIMARY KEY (contract, block)
);

CREATE INDEX IF NOT EXISTS transactions_type ON transactions USING HASH (type);
