version: '3'
services:
  kpi-tracker-grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning:Z
      - ../grafana:/var/lib/grafana/dashboards:Z
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/dashboard.json"
      GF_AUTH_ANONYMOUS_ENABLED: true
  kpi-tracker-db:
    image: postgres
    command: -c fsync=off
    environment:
      POSTGRES_DB: "kpi-tracker"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    shm_size: '4GB'
