# Assumes docker context is repository root, i.e. ../../ relative to this file.
*
!deps/concordium-rust-sdk
deps/concordium-rust-sdk/target
!kpi-tracker/*
kpi-tracker/target
kpi-tracker/grafana
kpi-tracker/*.md
