name: Fmt and Clippy

# This job runs rustfmt and clippy linting,

on:
  push:
    branches: main

  pull_request:
    branches: main

  workflow_dispatch: # allows manual trigger

env:
  RUST_FMT: nightly-2023-04-01-x86_64-unknown-linux-gnu
  RUST_CLIPPY: "1.74"

jobs:
  "lint_fmt":
    name: lint:fmt
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - wallet-proxy-load-simulator/Cargo.toml
          - state-compare/Cargo.toml
          - genesis-creator/Cargo.toml
          - id-verifier/Cargo.toml
          - kpi-tracker/Cargo.toml
          - chain-prometheus-exporter/Cargo.toml
          - recover-id-object/Cargo.toml
          - generator/Cargo.toml
          - wallet-connect-test-bench/smart-contract/Cargo.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup default ${{ env.RUST_FMT }}
          rustup component add rustfmt
      - name: Format
        run: |
          cargo fmt --manifest-path=${{ matrix.crates }} -- --check

  "lint_clippy":
    name: lint:clippy
    needs: "lint_fmt"
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - wallet-proxy-load-simulator/Cargo.toml
          - state-compare/Cargo.toml
          - genesis-creator/Cargo.toml
          - id-verifier/Cargo.toml
          - kpi-tracker/Cargo.toml
          - chain-prometheus-exporter/Cargo.toml
          - recover-id-object/Cargo.toml
          - generator/Cargo.toml
          - wallet-connect-test-bench/smart-contract/Cargo.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        run: |
          rustup default ${{ env.RUST_CLIPPY }}
          rustup component add clippy
      - name: Clippy
        run: |
          cargo clippy --manifest-path ${{ matrix.crates }} --locked -- -D warnings

