name: Build and test

on:
  push:
    branches: main

  pull_request:

  workflow_dispatch: # allows manual trigger

env:
  RUST_FMT_VERSION: nightly-2023-04-01-x86_64-unknown-linux-gnu

jobs:

  "rustfmt":
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#        with: todo ar needed?
#          submodules: recursive
      - name: Run cargo fmt
        run: |
          rustup +${{ env.RUST_FMT_VERSION }} component add rustfmt
          cargo +${{ env.RUST_FMT_VERSION }} fmt --all --check

  "clippy":
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Clippy
        run: |
          rustup component add clippy
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dependencies
        run: |
          cd notification-server
          make setup-db && make
      - name: Run tests
        run: |
          cargo test --locked --all-features --release
