name: Release workflow

on:
  release:
    types: [published]

env:
  RUST_VERSION: rust:1.70-buster
  ID_RECOVER_TOOL_NAME: id-recover-tool

jobs:

  build-and-push:
    if: startsWith(github.ref, "refs/tags/${{ env.ID_RECOVER_TOOL_NAME }}/")
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.ID_RECOVER_TOOL_NAME }}/scripts/Dockerfile
        push: true
        build-args: |
          build_image=${{ env.rust_version }}
        tags: concordium/recover-id-object:latest
        cache-from: type=registry,ref=concordium/recover-id-object:latest
        cache-to: type=inline
