name: Release workflow

on:
  workflow_dispatch:

env:
  RUST_VERSION: rust:1.74-buster

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    environment: release-recover-id-object
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Extract Cargo package version
      id: cargo_version
      run: |
        cd recover-id-object
        VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: recover-id-object/scripts/Dockerfile
        push: true
        build-args: |
          build_image=${{ env.RUST_VERSION }}
        tags: concordium/recover-id-object:${{ env.VERSION}}
